implemented %__find_{requires,provides}_filter and %filter_from_{requires,provides}
The first two macros provide general mechanism for find-requires
and find-provides filtering.  Any valid command or shell syntax can
be used - the command will be executed using "eval" within find-*
script.  The implementation in %___build_pre is not particular
beautiful (as it uses here-docs), but there seems to be no easy
way to quote for eval yet.

The second two commands are built on top of the first: they use
sed as a filtering tool.  The implementation is compatible with Fedora:
http://fedoraproject.org/wiki/Packaging:AutoProvidesAndRequiresFiltering

diff --git a/autodeps/linux.prov.in b/autodeps/linux.prov.in
--- a/autodeps/linux.prov.in
+++ b/autodeps/linux.prov.in
@@ -116,4 +116,15 @@ RunMethod()
 
 Info "running scripts ($methods)"
 RunMethods prov "$methods" RunMethod
-[ -z "$found" ] || (set +f; LC_COLLATE=C sort -u -m "$workdir"/*.deps) || exit 1
+
+if [ -n "$found" ]; then
+	(set +f && LC_ALL=C sort -u -m "$workdir"/*.deps) >"$workdir"/find-provides-deps || false
+	if [ -n "${RPM_FIND_PROVIDES_FILTER-}" ]; then
+		(eval "set -x; $RPM_FIND_PROVIDES_FILTER") <"$workdir"/find-provides-deps >"$workdir"/filter-provides-deps
+		[ $? = 0 ] || Fatal "filter failed"
+		(cd "$workdir" && diff -U1 find-provides-deps filter-provides-deps) >&2 ||:
+		cat "$workdir"/filter-provides-deps
+	else
+		cat "$workdir"/find-provides-deps
+	fi
+fi
diff --git a/autodeps/linux.req.in b/autodeps/linux.req.in
--- a/autodeps/linux.req.in
+++ b/autodeps/linux.req.in
@@ -109,7 +109,18 @@ export RPM_FINDPACKAGE_COMMANDS_LOG="$RPM_BUILD_ROOT"/.findpackage-commands
 
 Info "running scripts ($methods)"
 RunMethods req "$methods" RunMethod
-[ -z "$found" ] || (set +f; LC_COLLATE=C sort -u -m "$workdir"/*.deps) || exit 1
+
+if [ -n "$found" ]; then
+	(set +f && LC_ALL=C sort -u -m "$workdir"/*.deps) >"$workdir"/find-requires-deps || false
+	if [ -n "${RPM_FIND_REQUIRES_FILTER-}" ]; then
+		(eval "set -x; $RPM_FIND_REQUIRES_FILTER") <"$workdir"/find-requires-deps >"$workdir"/filter-requires-deps
+		[ $? = 0 ] || Fatal "filter failed"
+		(cd "$workdir" && diff -U1 find-requires-deps filter-requires-deps) >&2 ||:
+		cat "$workdir"/filter-requires-deps
+	else
+		cat "$workdir"/find-requires-deps
+	fi
+fi
 
 if [ -s "$RPM_FINDPACKAGE_COMMANDS_LOG" ]; then
 	LC_ALL=C sort -u -o "$RPM_FINDPACKAGE_COMMANDS_LOG"{,}
