cpp.req: recover missing once-only pushes using -dI
Hierarchical processing makes cpp.req more susceptible to "once-only
header" optimization.  To demonstrate the problem, I've implemented
some debugging facilities.  Here is how <gtk/gtk.h> is processed.

$ cpp.req -vv /usr/include/gtk-2.0/gtk/gtk.h
[...]
  Include gdk/gdk.h
+ Push /usr/include/gtk-2.0/gdk/gdk.h
    Include gdk/gdkapplaunchcontext.h
+   Push /usr/include/gtk-2.0/gdk/gdkapplaunchcontext.h
      Include gio/gio.h
!     Push /usr/include/glib-2.0/gio/gio.h
        Include gio/giotypes.h
        Push /usr/include/glib-2.0/gio/giotypes.h
          Include gio/gioenums.h
          Push /usr/include/glib-2.0/gio/gioenums.h
            Include glib-object.h
            Push /usr/include/glib-2.0/glib-object.h
              Include gobject/gbinding.h
              Push /usr/include/glib-2.0/gobject/gbinding.h
                Include glib.h
                Push /usr/include/glib-2.0/glib.h
[...]
+               Push /usr/include/gtk-2.0/gtk/gtkdebug.h
                  Include glib.h
                Pop
[...]
recovered glib.h -> /usr/include/glib-2.0/glib.h
recovered stdarg.h -> /usr/lib64/gcc/x86_64-alt-linux/4.5.3/include/stdarg.h
recovered time.h -> /usr/include/time.h
recovered glib-object.h -> /usr/include/glib-2.0/glib-object.h

In the output, "Include" lines annotate "#include" instructions which
are about to be processed by cpp; "Push" and "Pop" annotate actual
file operations performed by cpp.  Technically, "Include" annotations
are enabled via -dI option which installs cb_include callback in
gcc/c-ppoutput.c; "Push" and "Pop" are triggered in the guts of the
libcpp library.  The library has hardcoded optimization against repeated
inclusions.  According to "info cpp", "It remembers when a header file
has a wrapper #ifndef.  If a subsequent #include specifies that header,
and the macro in the #ifndef is still defined, it does not bother to
rescan the file at all."  (See should_stack_file in libcpp/files.c.)

This means that, normally, each "Include" should be followed by a
corresponding "Push".  However, due to "once-only header" optimization,
some includes are not followed by a push.  This means that the file
has already been pushed, and it happens to use a wrapper #ifndef.
Note that, in the output, this is exactly the case with <glib2.h>.

Also note that, in the output, files internal to the package are marked
with "+" on the left.  They are tracked down to the first non-packaged
file, which makes a dependency; these files are marked with "!".  The
problem with <glib2.h> is then that it gets first included in an
external file.  Later it is also included in an internal file, but
a "Push" is not triggered.  And since the internal file is subordinate
to <gtk/gtk.h> and is not going to be processed on its own, the
dependency on <glib2.h> is lost.

To recover missing pushes, we have to associate each include with the
first-time push.  In other words, we need a table which maintains a
(header -> filename) mapping; in the above example, the table will
contain (glib.h -> /usr/include/glib-2.0/glib.h).  Using this table,
we can ascertain that each internal #include produced a result.

Now, this might still have some corner cases: includes with
non-canonical header names probably will not be recovered, and it is not
clear whether <foo.h> and "foo.h" should be processed differently.
It works well enough in simple cases, though.

diff --git a/scripts/cpp.req.in b/scripts/cpp.req.in
--- a/scripts/cpp.req.in
+++ b/scripts/cpp.req.in
@@ -118,16 +118,16 @@ CppReq()
 	cflags=$(Cflags "$f")
 	Debug "$f: cflags:" $cflags
 
-	if ! "$cpp" -w $cxx $cflags "$f" >$tmpdir/out; then
+	if ! "$cpp" -w -dI $cxx $cflags "$f" >$tmpdir/out; then
 		if [ -n "$cxx" -o "$cxx_test" = failed ]; then
 			Warning "$f: cpp failed"
 			return 0
 		fi
 		Info "$f: cpp failed, trying c++ mode"
 		cxx='-x c++'
-		if ! "$cpp" -w $cxx $cflags "$f" >$tmpdir/out; then
+		if ! "$cpp" -w -dI $cxx $cflags "$f" >$tmpdir/out; then
 			if [ -z "$cxx_test" ]; then
-				"$cpp" -w $cxx < /dev/null > /dev/null 2>&1 &&
+				"$cpp" -w -dI $cxx < /dev/null > /dev/null 2>&1 &&
 					cxx_test=ok ||
 					cxx_test=failed
 			fi
@@ -137,11 +137,11 @@ CppReq()
 		fi
 	fi
 
-	# Keep only linemarks, unquote filenames.
-	sed -ni '/^#.* "\//{s/"//g;p}' $tmpdir/out
+	# Keep only linemarks and includes, strip filename quotes.
+	sed -ni '/^# .* "\//{s/"//g;p};/^#i.* ["<]/{s/[<">]//g;p}' $tmpdir/out
 
 	# Prepare the list of files in cpp output which are packaged in this subpackage.
-	cut -d' ' -f3 <$tmpdir/out |
+	awk '$1=="#" && $4==1 { print $3 }' <$tmpdir/out |
 		xargs -r --delimiter='\n' \
 		stat -c '%d,%i %n' |
 		sort -u >$tmpdir/iout
@@ -158,12 +158,29 @@ CppReq()
 			SP = 0
 			SPmark = 0
 			Stack[SP] = hdr
+			if (ENVIRON["RPM_SCRIPTS_DEBUG"] > 1)
+				DEBUG = 1
 			while ((getline <pf) > 0)
 				Packaged[$1] = 1
 		}
 		function Push(f) {
+			if (DEBUG)
+				printf "%c%*sPush %s\n",
+					Packaged[f] ? "+" : (SPmark == SP) ? "!" : " ",
+					SP * 2 + 1, "", f >"/dev/stderr"
+			# Print dependency.
 			if (SPmark == SP && !Packaged[f] && !Printed[f]++)
 				print f
+			# Update header->file mapping.
+			h = ExpectPush
+			if (!(h in h2f))
+				h2f[h] = f
+			# Further sync with the Include.
+			if (SPmark == SP) {
+				delete NeedPush[h]
+				h2f[h] = f
+			}
+			# Update the stack.
 			if (SPmark == SP && Packaged[f])
 				SPmark++
 			Stack[++SP] = f
@@ -174,13 +191,42 @@ CppReq()
 					prog, hdr, Stack[SP], f >"/dev/stderr"
 			if (SPmark > SP)
 				SPmark = SP
+			if (DEBUG)
+				printf "%*sPop\n",
+					SP * 2 + 2, "" >"/dev/stderr"
 		}
-		$4==1 { Push($3) }
-		$4==2 { Pop($3) }
+		function Include(h) {
+			if (DEBUG)
+				printf "%*sInclude %s\n",
+					SP * 2 + 2, "", h >"/dev/stderr"
+			if (SPmark == SP)
+				NeedPush[h] = 1
+			ExpectPush = h
+		}
+		$1=="#" && $4==1 { Push($3) }
+		$1=="#" && $4==2 { Pop($3) }
+		$1~/^#i/ { Include($2) }
 		END {
 			if (SP > 0)
 				printf "%s: %s: non-empty stack, top %s\n",
 					prog, hdr, Stack[SP] >"/dev/stderr"
+			# Recover missing pushes due to once-only optimization.
+			for (h in NeedPush) {
+				f = h2f[h]
+				if (f) {
+					if (!Packaged[f] && !Printed[f]++) {
+						if (DEBUG)
+							printf "recovered %s -> %s\n",
+								h, f >"/dev/stderr"
+						print f
+					}
+				}
+				else {
+					if (DEBUG)
+						printf "cannot recover %s\n",
+							h >"/dev/stderr"
+				}
+			}
 		}'
 	# The list of required files is now ready.
 	sort -u -o $tmpdir/req{,}
