adapted pkgconfig.req and pkgconfig.prov
Also enhanced the scripts by using pkg-config --print-errors, because
pkg-config is silent by default.  Also added checks for pkg-config exit
status and valid output.

Also changed the order: libdir/pkgconfig:datadir/pkgconfig instead of
datadir/pkgconfig:libdir/pkgconfig, according to pkg-config(1).

diff --git a/scripts/pkgconfig.req.in b/scripts/pkgconfig.req.in
--- a/scripts/pkgconfig.req.in
+++ b/scripts/pkgconfig.req.in
@@ -1,6 +1,7 @@
-#!/bin/sh -ef
+#!/bin/sh -efu
 #
 # Copyright (C) 2006  Dmitry V. Levin <ldv@altlinux.org>
+# Copyright (C) 2007  Alexey Tourbin <at@altlinux.org>
 #
 # This program is free software; you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -17,12 +18,27 @@
 # Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA.
 #
 
-#. @RPMCONFIGDIR@/functions
-#ValidateBuildRoot
+. @RPMCONFIGDIR@/functions
 
-for f; do
-	PKG_CONFIG_PATH=$RPM_BUILD_ROOT/usr/share/pkgconfig:$RPM_BUILD_ROOT$RPM_LIBDIR/pkgconfig:/usr/share/pkgconfig:$RPM_LIBDIR/pkgconfig \
-		pkg-config --print-requires "$f" |while read name op version; do
-			echo "pkgconfig($name) $op $version"
-		done
-done
+[ -n "${RPM_LIBDIR-}" ] || RPM_LIBDIR=`rpm --eval %_libdir`
+PKG_CONFIG_PATH=$RPM_LIBDIR/pkgconfig:/usr/share/pkgconfig
+[ -z "${RPM_BUILD_ROOT-}" ] ||
+PKG_CONFIG_PATH=$RPM_BUILD_ROOT$RPM_LIBDIR/pkgconfig:$RPM_BUILD_ROOT/usr/share/pkgconfig:$PKG_CONFIG_PATH
+export PKG_CONFIG_PATH
+
+PkgconfigReq()
+{
+	local f="$1" out=; shift
+	out=$(pkg-config --print-errors --print-requires "$f")
+	[ -n "$out" ] || return 0
+	echo "$out" |while read -r line; do
+		set -- $line
+		case $# in
+			1) echo "pkgconfig($1)" ;;
+			3) echo "pkgconfig($1) $2 $3" ;;
+			*) Fatal "$f: invalid pkg-config output: $line"
+		esac
+	done
+}
+
+ArgvFileAction PkgconfigReq "$@"
