shell.req: reworked
Now "sh --rpm-requires" failures are always verbose:

$ ln -s /usr/lib/rpm @RPMCONFIGDIR@
$ scripts/shell.req.in /usr/lib/rpm/tcl.req
/usr/lib/rpm/tcl.req: line 32: syntax error near unexpected token `}'
/usr/lib/rpm/tcl.req: line 32: `}'
shell.req.in: /usr/lib/rpm/tcl.req is ${RPM_TCLSH:-/usr/bin/tclsh} script!
shell.req.in: /usr/lib/rpm/tcl.req: invalid pathname ${RPM_TCLSH:-/usr/bin/tclsh}
$ echo $?
0
$

$ scripts/shell.req.in /usr/bin/perldoc
/usr/bin/perldoc: line 6: syntax error near unexpected token `Pod::Perldoc-'
/usr/bin/perldoc: line 6: `exit( Pod::Perldoc->run() );'
shell.req.in: /usr/bin/perldoc: /bin/sh --rpm-requires failed
$ echo $?
1
$

diff --git a/scripts/shell.req.in b/scripts/shell.req.in
--- a/scripts/shell.req.in
+++ b/scripts/shell.req.in
@@ -1,6 +1,7 @@
 #!/bin/sh -efu
 #
 # Copyright (C) 2000,2003  Dmitry V. Levin <ldv@altlinux.org>
+# Copyright (C) 2007       Alexey Tourbin <at@altlinux.org>
 #
 # This program is free software; you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -18,44 +19,48 @@
 #
 
 . @RPMCONFIGDIR@/functions
-[ $# -eq 1 ] && [ -n "$1" -a -z "${1##/*}" ] ||
-	{ ArgvFileAction "$0" "$@"; exit; }
-
-file="$1"
-fname="${file##${RPM_BUILD_ROOT-}}"
-dname="${fname%/*}"
-#extra=
-
-t="$(file -b "$file")" || Fatal "${t:-$f: file type not available}"
-
-case "$t" in
-	*"Bourne-Again shell script text"*)
-		FIND_REQ='/bin/bash --rpm-requires' ;;
-	*" bash script text"*)
-		FIND_REQ='/bin/bash --rpm-requires' ;;
-	*)
-		FIND_REQ='/bin/sh --rpm-requires' ;;
-esac
-
-# Make sure that this shell supports the rpm-requires feature.
-$FIND_REQ </dev/null >/dev/null
-
-if ! reqs="$($FIND_REQ "$file" 2>/dev/null)"; then
-	if egrep -vs '^(#|$)' "$file" 2>/dev/null |head -1 |grep -qs '^[ 	]*exec '; then
-		reqs="$(printf %s\\n "$reqs" |head -1)"
-		#extra="$(printf %s\\n "$reqs" |sed -e 's/^\(executable\)(\(.*\))$/\2/g')"
-	else
-		reqs="$($FIND_REQ "$file")"
-	fi
-fi
-reqs="$(printf %s\\n "$reqs" |sed -n 's/^\(sh\|bash\|executable\)(\(.*\))$/\2/p' |LC_COLLATE=C sort -u)"
-[ -n "$reqs" ] || exit 0
-
 . @RPMCONFIGDIR@/find-package
 
-FindReqs()
+ShellReq()
 {
-	for r in "$@"; do
+	local f="$1"; shift
+
+	local t sh
+	t=$(file -b "$f") || Fatal "${t:-$f: file type not available}"
+	case "$t" in
+		*"Bourne-Again shell script text"*)
+			sh=/bin/bash ;;
+		*" bash script text"*)
+			sh=/bin/bash ;;
+		*)
+			sh=/bin/sh ;;
+	esac
+	$sh --rpm-requires </dev/null >/dev/null ||
+		Fatal "$sh interpreter does not support --rpm-requires feature"
+
+	local reqs line1
+	if ! reqs="$($sh --rpm-requires "$f")"; then
+		# sh --rpm-requires failed, and stderr is already there.
+		# We are almost dead.  The last chance to escape is to see
+		# if the shell is used only to re-exec another interpreter, e.g.
+		#	exec tclsh "$0" "$@"
+		if line1=$(egrep -m1 -v '^[[:space:]]*(#|$)' "$f"); then
+			set -- $line1
+			if [ $# -gt 1 ] && [ "$1" = exec ]; then
+				Info "$f is $2 script!"
+				FindPackage "$f" "$2"
+				return 0
+			fi
+		fi
+		Fatal "$f: $sh --rpm-requires failed"
+	fi
+
+	reqs="$(printf %s\\n "$reqs" |sed -n 's/^\(sh\|bash\|executable\)(\(.*\))$/\2/p' |LC_COLLATE=C sort -u)"
+
+	local dname r
+	dname=${f#${RPM_BUILD_ROOT-}}
+	dname=${dname%/*}
+	for r in $reqs; do
 		if [ -z "${r/*\$*}" ]; then
 			continue
 		fi
@@ -68,15 +73,9 @@ FindReqs()
 		elif grep -qs -Fx -- "$r" "$dname/.provides.sh"; then
 			printf %s\\n "$dname($r)"
 		else
-			FindPackage "$file" "$r"
+			FindPackage "$f" "$r"
 		fi
 	done
 }
 
-# Find requires
-found="$(FindReqs $reqs)"
-
-# And print them.
-printf %s "$found" |LC_COLLATE=C sort -u
-
-# TODO: more analysis based on $extra
+ArgvFileAction ShellReq "$@"
